/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        pm: {
          primary: "#0F4C81",
          "primary-light": "#E8F1F8",
          "primary-hover": "#0D3F6B",
          "primary-dark": "#0A3357",
          accent: "#2A9D8F",
          "accent-light": "#E6F5F3",
          "accent-hover": "#238B7E",
          purple: "#6C5CE7",
          "purple-light": "#EDE9FE",
          orange: "#E9A23B",
          "orange-light": "#FDF3E0",
          success: "#27AE60",
          "success-light": "#E8F8EF",
          error: "#E74C3C",
          "error-light": "#FDEDEC",
          neutral: "#94A3B8",
          "bg-primary": "#F5F7FA",
          "bg-card": "#FFFFFF",
          "bg-dark": "#0F172A",
          "bg-overlay": "rgba(15, 23, 42, 0.5)",
          "text-primary": "#1E293B",
          "text-secondary": "#64748B",
          "text-muted": "#94A3B8",
          "text-inverse": "#FFFFFF",
          "border-color": "#E2E8F0",
          "border-focus": "#0F4C81",
        },
      },
      fontFamily: {
        heading: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        "pm-sm": "6px",
        "pm-md": "10px",
        "pm-lg": "14px",
        "pm-xl": "20px",
        "pm-full": "9999px",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "pm-sm": "0 1px 3px rgba(0,0,0,0.04)",
        "pm-md": "0 4px 12px rgba(0,0,0,0.06)",
        "pm-lg": "0 8px 24px rgba(0,0,0,0.08)",
        "pm-xl": "0 16px 48px rgba(0,0,0,0.12)",
        "pm-primary": "0 4px 16px rgba(15, 76, 129, 0.2)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "hero-bg-drift": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-20px)" },
        },
        "hue-shift": {
          "0%": { filter: "hue-rotate(-5deg)" },
          "50%": { filter: "hue-rotate(5deg)" },
          "100%": { filter: "hue-rotate(-5deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "hero-bg-drift": "hero-bg-drift 30s linear infinite",
        "hue-shift": "hue-shift 8s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
